### ISSUE TITLE
Missing golf_trail.

### ISSUE THREAD

**Issue by TomSlezakowski** [utkarsh1148/Golf-Trail#2]
Hey!

Seems like Golf_Trail (and other) modules were removed from github yesterday... I just sat down to take a look at this in action however the main code still requires them.

Any update on what's happening?

Thanks,
Tom

**Comment by utkarsh1148** [comment]
Hey 
I have consciously deleted many files so that the main algorithm can't be simply copied as it is. You can mail me i might give you my files.
Mail ID : utkarsh1148@gmail.com
